### ISSUE TITLE
incompatible with vjs 4.12, which use TextTrackList instead of TextTrack Array

### ISSUE THREAD

**Issue by i-c0112** [walsh9/videojs-transcript#3]
Caught this exception: 
"TypeError: my.tracks.forEach is not a function"

And found that videojs 4.12 implements textTracks() differently from 4.9 did.
Returned TextTrackList object has no function forEach

**Comment by walsh9** [comment]
Thanks for the reminder. I've started working on updating this to work with vjs 4.12 today.

**Comment by walsh9** [comment]
A few details about the fixes here:
http://walsh9.net/projects/loading-text-tracks-in-video-js-4-12
